stages:
  - deploy

# 部署测试服务器
deploy_dev:
  stage: deploy
  tags:
    - anther-tag
  only:
    - master
  script:
    - echo 'mvn package'
    - whoami
    - echo $HOME
    - cat /home/admin/restart.sh
    - mvn package
    - cp /home/gitlab-runner/builds/6f0bdf8b/0/3miky/columbu/target/3miky-columbu-0.0.1-SNAPSHOT.jar /home/www/columbu/3miky-columbu-0.0.1-SNAPSHOT.jar
    - java -jar /home/www/columbu/3miky-columbu-0.0.1-SNAPSHOT.jar



