stages:
  - deploy

# 部署测试服务器
deploy_dev:
  stage: deploy
  tags:
    - anther-tag
  only:
    - master
  script:
    - echo 'mvn package'
    - whoami
    - echo $HOME
    - echo $PATH
    - type mvn
    - mvn package
