server:
  port: 8080
spring:
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: bvvy288
    url: jdbc:mysql://localhost:3306/grocery
  profiles:
    active: default
  application:
    name: ying
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    org:
      springframework:
       web: debug
       security: debug
alibaba:
  oss:
    end-point: your
    access-key-id: your
    secret-access-key: your
    bucket-name: your
    file-host: your
qiniu:
  oss:
    access-key: OobyLRT8f_jxHigOjujGaGtwvLHJo8LSwzTWUQbi
    secret-key: W1HuqgbOFQbWYkZYSyxrEqNb27ajrrRl39d-BQmq
    bucket: ying
    bucket-domain: http://pgc6voj4f.bkt.clouddn.com
dic:
  status:
    enable: Y
    disable: N
  cost-type:  # 报价类型
    general: general # 常规
    special: special # 特殊
  publish-status: # 文章的发布状态
    publish: publish
    draft: draft
  container-type:
    general: G
    special: S
divide:
  dic:
    status:
      order:
        waiting-confirm: waiting_confirm
        waiting-deliver: waiting_deliver
        waiting-receive: waiting_receive
        finish: finish
      application:
        waiting-confirm: waiting_confirm
        finish: finish
    type:
      warehouse:
        pair: pair
        prod: prod
  defaults:
    avatar: https://avatars2.githubusercontent.com/u/15703262?s=460&v=4
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/v1/user
