server:
  port: 8090
spring:
  jpa:
    database-platform: MYSQL
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test2018
    password: mj2018!@#
    url: jdbc:mysql://120.79.32.147:3306/columbu
  profiles:
    active: default
  application:
    name: columbu
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8090/user
logging:
  level:
    org:
      springframework:
       web: debug
       security: debug
alibaba:
  oss:
    end-point: http://oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAIHxopb8AXx7iF
    secret-access-key: b2PrRJQgxCeMqhGL1y9QkKVebBV0rJ
    bucket-name: mj-columbu
    file-host: http://mj-columbu.oss-cn-shenzhen.aliyuncs.com/
dic:
  status:
    enable: Y
    disable: N
  cost-type:  # 报价类型
    general: general # 常规
    special: special # 特殊
  publish-status: # 文章的发布状态
    publish: publish
    draft: draft