server:
  port: 9520
spring:
  jpa:
    database-platform: MYSQL
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: your
    password: your
    url: your
  profiles:
    active: default
  application:
    name: columbu
  jackson:
    default-property-inclusion: non_null
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8090/user
logging:
  level:
    org:
      springframework:
       web: debug
       security: debug
alibaba:
  oss:
    end-point: your
    access-key-id: LTAIHxopb8AXx7iF
    secret-access-key: your
    bucket-name: your
    file-host: your
dic:
  status:
    enable: Y
    disable: N
  cost-type:  # 报价类型
    general: general # 常规
    special: special # 特殊
  publish-status: # 文章的发布状态
    publish: publish
    draft: draft
  container-type:
    general: G
    special: S