server:
  port: 11111
spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bvvyeh288
    url: jdbc:postgresql://localhost:5432/grocery
  profiles:
    active: default
  application:
    name: columbu
  jackson:
    default-property-inclusion: non_null
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8090/user
logging:
  level:
    org:
      springframework:
       web: debug
       security: debug
alibaba:
  oss:
    end-point: your
    access-key-id: your
    secret-access-key: your
    bucket-name: your
    file-host: your
dic:
  status:
    enable: Y
    disable: N
  cost-type:  # 报价类型
    general: general # 常规
    special: special # 特殊
  publish-status: # 文章的发布状态
    publish: publish
    draft: draft
  container-type:
    general: G
    special: S