server:
  port: 8090
spring:
  jpa:
    database-platform: MYSQL
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test2018
    password: mj2018!@#
    url: jdbc:mysql://120.79.32.147:3306/columbu
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: default
  application:
    name: columbu
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8090/user
logging:
  level:
    org:
      springframework:
       web: debug
       security: debug
dic:
  status:
    enable: Y
    disable: N