#dataSource

#spring.datasource.password=bvvy288
#spring.datasource.url=jdbc:mysql://localhost:3306/bvvy_divide?userUnicode=true&characterEncoding=utf8&useSSL=true
#spring.datasource.username=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#spring.jpa.show-sql= true
#spring.jpa.database= mysql
#spring.jpa.hibernate.ddl-auto= update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
#logging.level.com.mj = debug
server:
  port: 8090
spring:
  jpa:
    database-platform: MYSQL
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test2018
    password: mj2018!@#
    url: jdbc:mysql://120.79.32.147:3306/columbu
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8090/user
logging:
  level:
    org:
      springframework:
       web: debug
       security: debug
