server:
  port: 11111
spring:
  jpa:
    database-platform: POSTGRESQL
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bvvyeh288
    url: jdbc:postgresql://localhost:5432/grocery
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:12222/user
logging:
  level:
    org:
      springframework:
       web: debug
       security: debug
